### ISSUE TITLE
Example throws an error

### ISSUE THREAD

**Issue by syleishere** [ChangJoo-Park/flutter_foreground_service_plugin#23]
C:\flutter\musicplayer\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:21: error: FlutterForegroundPlugin() has private access in FlutterForegroundPlugin
    flutterEngine.getPlugins().add(new changjoopark.com.flutter_foreground_plugin.FlutterForegroundPlugin());
                                   ^
1 error

**Comment by syleishere** [comment]
Arrow pointing at the "new" statement, probably to remove it.

**Comment by jja08111** [comment]
Same issue

**Comment by boldt** [comment]
What's the status of this issue and and Pull Request #25?
We're trying to migrate to flutter 2.0 and this stops us to continue with null-safety.

**Comment by wasiqwiqar** [comment]
Trying to use `flutter_foreground_service_plugin` with a project and keep running into this same issue. This is keeping us from continuing on with flutter 2.0 as well

**Comment by boldt** [comment]
Right now, I am using the Pull Request #25 as git-dependency in my code.

Instead of ...

```
flutter_foreground_plugin: ^0.6.0
```

... use ...

```
  flutter_foreground_plugin:
    git:
      url: https://github.com/jja08111/flutter_foreground_service_plugin.git
      ref: 8a09c7b0aeb9d31204147fe6ee126c8a52471e3a
```

... until the PR is merged.
