### ISSUE TITLE
FlutterForegroundPlugin.java uses or overrides a deprecated API

### ISSUE THREAD

**Issue by boldt** [ChangJoo-Park/flutter_foreground_service_plugin#32]
**Issue**

We migrated to flutter 2.0. Now we're getting the following warning, while building our app:

```
Note: C:\Users\<USER>\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flutter_foreground_plugin-0.8.0\android\src\main\java\changjoopark\com\flutter_foreground_plugin\FlutterForegroundPlugin.java uses or overrides a deprecated API.
```

**Environment**

* flutter 2.2.0
* flutter_foreground_plugin: 0.6.0 + 0.8.0

**Comment by zmsp** [comment]
+1

**Comment by m-zaguette** [comment]
+1

This error don't let build apk --release. Does anyone know how to make that please?

**Comment by m-zaguette** [comment]
+1

**Comment by deepak-ariceum** [comment]
Add this to pubspec under dependencies:

```
flutter_foreground_plugin:
    git:
      url: https://github.com/jja08111/flutter_foreground_service_plugin.git
      ref: 8a09c7b0aeb9d31204147fe6ee126c8a52471e3a
```
